import { Beiruti } from "next/font/google";
import "./globals.css";


const beiruti = Beiruti ({
  variable: "--font-beiruti",
  subsets: ["arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${beiruti.variable} antialiased beiruti bg-[#041728] `}
      >
        {children}
      </body>
    </html>
  );
}
